package com.myspace.icaruus_mvp;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Customer")
public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "fullName")
	private java.lang.String fullName;
	@org.kie.api.definition.type.Label(value = "fullAddress")
	private java.lang.String fullAddress;

	public Customer() {
	}

	public java.lang.String getFullName() {
		return this.fullName;
	}

	public void setFullName(java.lang.String fullName) {
		this.fullName = fullName;
	}

	public java.lang.String getFullAddress() {
		return this.fullAddress;
	}

	public void setFullAddress(java.lang.String fullAddress) {
		this.fullAddress = fullAddress;
	}

	public Customer(java.lang.String fullName, java.lang.String fullAddress) {
		this.fullName = fullName;
		this.fullAddress = fullAddress;
	}

}