package com.myspace.icaruus_mvp;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("manufacturer - not sure if manufacturers can sign up for an account using this")
public class Manufacturer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public Manufacturer() {
	}

}