package com.myspace.icaruus_mvp;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("ManufacturerFormData")
public class ManufacturerFormData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Status")
	private java.util.List<java.lang.String> status;
	@org.kie.api.definition.type.Label(value = "Comment")
	private java.lang.String comment;

	public ManufacturerFormData() {
	}

	public java.util.List<java.lang.String> getStatus() {
		return this.status;
	}

	public void setStatus(java.util.List<java.lang.String> status) {
		this.status = status;
	}

	public java.lang.String getComment() {
		return this.comment;
	}

	public void setComment(java.lang.String comment) {
		this.comment = comment;
	}

	public ManufacturerFormData(java.util.List<java.lang.String> status,
			java.lang.String comment) {
		this.status = status;
		this.comment = comment;
	}

}