package com.myspace.icaruus_mvp;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("OrderItem")
public class OrderItem implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Item Name")
	private java.lang.String itemName;
	@org.kie.api.definition.type.Label(value = "Quantity of item")
	private java.lang.Integer quantity;
	@org.kie.api.definition.type.Label(value = "Pattern file link")
	private java.lang.String link;

	public OrderItem() {
	}

	public java.lang.String getItemName() {
		return this.itemName;
	}

	public void setItemName(java.lang.String itemName) {
		this.itemName = itemName;
	}

	public java.lang.Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(java.lang.Integer quantity) {
		this.quantity = quantity;
	}

	public java.lang.String getLink() {
		return this.link;
	}

	public void setLink(java.lang.String link) {
		this.link = link;
	}

	public OrderItem(java.lang.String itemName, java.lang.Integer quantity,
			java.lang.String link) {
		this.itemName = itemName;
		this.quantity = quantity;
		this.link = link;
	}

}