package com.myspace.icaruus_mvp;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("OrderApplication")
public class OrderApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Customer")
	private com.myspace.icaruus_mvp.Customer customer;
	@org.kie.api.definition.type.Label(value = "Order Item Details")
	private com.myspace.icaruus_mvp.OrderItem orderItemDetails;

	public OrderApplication() {
	}

	public com.myspace.icaruus_mvp.Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(com.myspace.icaruus_mvp.Customer customer) {
		this.customer = customer;
	}

	public com.myspace.icaruus_mvp.OrderItem getOrderItemDetails() {
		return this.orderItemDetails;
	}

	public void setOrderItemDetails(
			com.myspace.icaruus_mvp.OrderItem orderItemDetails) {
		this.orderItemDetails = orderItemDetails;
	}

	public OrderApplication(com.myspace.icaruus_mvp.Customer customer,
			com.myspace.icaruus_mvp.OrderItem orderItemDetails) {
		this.customer = customer;
		this.orderItemDetails = orderItemDetails;
	}

}